added more golang paths to search for `hexokinase` binary
RRethy/vim-hexokinase pull request #89
Opened 2021-12-27 15:27 UTC by BourgeoisBear

2021-12-27 19:39 UTC, RRethy requested changes

2021-12-27 19:39 UTC, RRethy commented on plugin/hexokinase.vim
> +	let lPaths = [
snake-case for variables, also `lPaths` isn't a great variable name.

2021-12-28 01:06 UTC, BourgeoisBear commented
how is this?

2021-12-28 12:02 UTC, BourgeoisBear commented
After thinking about this, I've really just put another hack on top of your hack.  Using $PATH first would be the right thing to do.  Golang people have already appended their `go/bin` (wherever that may be) to the $PATH.  Non-golang people will have to install the compiler anyway, and we can always fall-back to the default `$HOME/go/bin` for them.

vim-go has a `:GoInstallBinaries` command to `go get` everything, honoring the user's preferred `go/bin` location.  As-is, getting this stowed to a new box is very manual.

Before I change anything, Yea or Nay?

2021-12-29 17:28 UTC, RRethy commented
I'd rather not add much logic here, the dependency is vendor'd so there's no expectation that the user has it on their path. `$GOPATH` was just a relic from when the binary wasn't vendor'd. Right now, I'm actually no longer inclined to to merging this PR after giving it a bit more thought, is there a specific reason the vendor'd dependency doesn't work for you?

2021-12-29 21:38 UTC, BourgeoisBear commented
Yes.  That's what I'm saying.  Abandon this pull request.  I'm suggesting a different approach.

1) Current user experience on new box:
  - open vim
  - get 'make hexokinase' error
  - leave vim
  - cd .vim/pack/plugins/start/vim-hexokinase
  - make hexokinase
  - go back to vim & continue

2) Proposed experience:
- open vim
- get 'please run :HexokinaseInstall' error 
- :HexokinaseInstall (which just does a go get `github.com/RRethy/hexokinase` behind the scenes)

As for paths, with B, we can just lean on the system path and a proper golang installation `if executable('hexokinase')`, and if that fails, assume the default go build destination of `$HOME/go/bin`.

This is just a suggestion now, since I just finished hot-rodding https://github.com/lilydjwg/colorizer to be fast enough, and it's pure vimscript, which solves my problem.

2021-12-29 21:38 UTC, closed without merging

2021-12-29 21:57 UTC, RRethy commented
For me those two experiences are the same, and this will be the case for anyone with a decent plugin manager which will handle this stuff for you. The issue with `go get` is a lack of versioning.

2021-12-29 22:20 UTC, BourgeoisBear commented
pkg.go.dev

```sh
export GO111MODULE=on
go install github.com/RRethy/hexokinase@v0.0.0-20200121161234-b345a18ba387
```